version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
      args:
        - PIP_INDEX_URL
    command: >
      bash -c "
      python manage.py makemigrations && 
      python manage.py runserver"
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file: .env
    restart: always